### ISSUE TITLE
geddy jake db:migrate fails due to user auth issue

### ISSUE THREAD

**Issue by bhgraham** [dfmcphee/simplifeed#4]
Ran across your project and was trying to install it and ran across this issue:
First off, it looks like its missing some steps like edit the config/development.js file from install instructions.

After I resolved that, I ran into this:

``` bash
bman@lightmyfire:~/simplifeed$ geddy jake db:migrate --trace
jake aborted.
TypeError: Cannot read property 'successRedirect' of undefined
    at Object.<anonymous> (/home/bman/simplifeed/app/helpers/passport/actions.js:4:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/bman/simplifeed/app/helpers/passport/index.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
bman@lightmyfire:~/simplifeed$ 

```

Thanks for any help!

**Comment by dfmcphee** [comment]
Hi, thanks for checking the project out. It looks like your are missing that property in your secrets.json file. Take a look at the sample file in the config folder for an example of what it should look like. I updated the getting started to mention this as well.
